import json

cogr1_questions = [
    {
        "id": "cogr1-q1",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 1,
        "questionText": "I. Yer çekiminin Trabzon'da Erzurum'a göre fazla olması\nII. Aynı anda farklı mevsimlerin yaşanması\nIII. Orografik yağışların görülmesi\nIV. Batı'dan doğuya gidildikçe Güneş'in daha erken doğması\n\nYukarıda verilen özelliklerden hangileri mutlak, hangileri göreceli konumun sonuçlarındandır?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Mutlak: I - III / Göreceli: II - IV"},
            {"key": "B", "text": "Mutlak: I - II / Göreceli: III - IV"},
            {"key": "C", "text": "Mutlak: II - IV / Göreceli: I - III"},
            {"key": "D", "text": "Mutlak: III - IV / Göreceli: I - II"},
            {"key": "E", "text": "Mutlak: I - IV / Göreceli: II - III"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>I (Enlem) ve IV (Boylam) mutlak konumun; II ve III (Yer şekilleri/Yükselti) göreceli konumun sonucudur."
    },
    {
        "id": "cogr1-q2",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 2,
        "questionText": "Bir yerin özel (göreceli) konumunun incelenmesinde aşağıdakilerden hangisinin bilinmesi şart değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Karalar üzerindeki yeri"},
            {"key": "B", "text": "Denizlere göre yeri"},
            {"key": "C", "text": "Kutuplara göre yeri"},
            {"key": "D", "text": "Yer altı zenginlikleri"},
            {"key": "E", "text": "Yükseltisi"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Kutuplara ve Ekvator'a göre yer mutlak (matematik) konum ile ilgilidir."
    },
    {
        "id": "cogr1-q3",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 3,
        "questionText": "Sinop'ta Kutup Yıldızı'nın görünüm açısının Hakkâri'den daha büyük olması aşağıdakilerden hangisiyle açıklanabilir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Yer şekillerinin sade olması"},
            {"key": "B", "text": "Deniz kenarında olması"},
            {"key": "C", "text": "Enlem itibarıyla daha kuzeyde olması"},
            {"key": "D", "text": "Tan ve grup süresinin daha uzun olması"},
            {"key": "E", "text": "Çizgisel hızın daha yavaş olması"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Kutup Yıldızı'nın görünüm açısı bulunulan yerin Kuzey enlem derecesine eşittir. Sinop (42° K) daha kuzeydedir."
    },
    {
        "id": "cogr1-q4",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 4,
        "questionText": "Aşağıda matematik konumları verilen noktalardan hangisi Türkiye sınırları içinde yer alır?\n(Türkiye: 36°-42° Kuzey Paralelleri ile 26°-45° Doğu Meridyenleri)",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "45° Doğu – 40° Kuzey"},
            {"key": "B", "text": "40° Doğu – 35° Kuzey"},
            {"key": "C", "text": "26° Batı – 42° Kuzey"},
            {"key": "D", "text": "44° Doğu – 26° Kuzey"},
            {"key": "E", "text": "37° Batı – 37° Kuzey"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>45° Doğu - 40° Kuzey noktası Türkiye sınırları içerisindedir (Iğdır civarı)."
    },
    {
        "id": "cogr1-q5",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 5,
        "questionText": "• Akdeniz ikliminin görülmesi\n• Tarım ürünlerinin çeşitli olması\n• Orografik yağışların görülmesi\n• Batı rüzgârlarının görülmesi\n• Aynı anda dört mevsimin yaşanması\n\nYukarıda verilen özelliklerden kaç tanesi Türkiye'nin orta kuşakta yer almasının sonuçlarındandır?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "1"},
            {"key": "B", "text": "2"},
            {"key": "C", "text": "3"},
            {"key": "D", "text": "4"},
            {"key": "E", "text": "5"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Akdeniz iklimi ve Batı rüzgârları (A-B-C-D kuralı) Orta Kuşak sonucudur (2 tanesi)."
    },
    {
        "id": "cogr1-q6",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 6,
        "questionText": "Aşağıdakilerden hangisi Türkiye'nin enleme bağlı matematik konum sonuçları arasında yer almaz?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Gölge yönünün daima kuzeyi göstermesi"},
            {"key": "B", "text": "21 Haziran'da Antalya'nın gündüz süresinin Ankara'dan kısa olması"},
            {"key": "C", "text": "Güneş ışınlarının hiçbir zaman dik açı ile gelmemesi"},
            {"key": "D", "text": "Aynı anda tek ortak saatin kullanılması"},
            {"key": "E", "text": "Fiyort ve skyer kıyı tiplerine rastlanılmaması"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Aynı anda tek ortak saat kullanılması Doğu-Batı yönlü boylam genişliğinin az olması sonucudur."
    },
    {
        "id": "cogr1-q7",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 7,
        "questionText": "Güneş ışınlarının yere düşme açısı küçüldükçe atmosferdeki tutulma oranı artmış olur.\n\nBuna göre, yukarıdaki Türkiye haritasında belirtilen illerden hangisinde yıl boyunca Güneş ışınlarının atmosferdeki tutulma oranı en fazladır?",
        "hasImage": True,
        "image": "assets/questions/cogr1_q7_map.png",
        "options": [
            {"key": "A", "text": "İzmir"},
            {"key": "B", "text": "Antalya"},
            {"key": "C", "text": "Sivas"},
            {"key": "D", "text": "Adapazarı"},
            {"key": "E", "text": "Iğdır"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Adapazarı haritada en kuzeyde yer aldığı için Güneş ışınlarını en dar açıyla alır ve atmosferde tutulma en fazla olur."
    },
    {
        "id": "cogr1-q8",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 8,
        "questionText": "Aşağıdaki kentlerin hangisinden geçen paralel dairesinin boyu diğerlerine göre daha uzundur?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Hatay"},
            {"key": "B", "text": "İzmir"},
            {"key": "C", "text": "Iğdır"},
            {"key": "D", "text": "Konya"},
            {"key": "E", "text": "Sinop"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>Paralel dairelerinin boyu Ekvator'dan kutuplara doğru kısalır. En güneydeki Hatay'da paralel boyu en uzundur."
    },
    {
        "id": "cogr1-q9",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 9,
        "questionText": "Bolu'dan Muğla'ya giden bir gözlemci;\nI. Yerel saat\nII. Ulusal saat\nIII. Gölge boyu\ngibi özelliklerden hangilerinde değişiklik gözlemlemez?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Yalnız I"},
            {"key": "B", "text": "Yalnız II"},
            {"key": "C", "text": "Yalnız III"},
            {"key": "D", "text": "I ve II"},
            {"key": "E", "text": "II ve III"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Türkiye'nin her yerinde ortak (ulusal) saat (45° D Iğdır) kullanıldığı için ulusal saat değişmez."
    },
    {
        "id": "cogr1-q10",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 10,
        "questionText": "Yukarıdaki haritada gösterilen kentlerden (Sinop, Kayseri, Hatay) hangisinde yıl boyunca gece ile gündüz arasındaki zaman farkı daha azdır? Neden?",
        "hasImage": True,
        "image": "assets/questions/cogr1_q10_map.png",
        "options": [
            {"key": "A", "text": "Sinop – Ekvator'a daha uzak olduğu için"},
            {"key": "B", "text": "Iğdır – Güneş daha erken doğduğu için"},
            {"key": "C", "text": "Hatay – Ekvator'a yakın olduğu için"},
            {"key": "D", "text": "İzmir – Başlangıç meridyenine yakın olduğu için"},
            {"key": "E", "text": "Kayseri – Türkiye'nin orta kesiminde yer aldığı için"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Ekvator'da yıl boyu 12 saat gece 12 saat gündüz yaşanır. Ekvator'a en yakın olan Hatay'da fark en azdır."
    },
    {
        "id": "cogr1-q11",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 11,
        "questionText": "I. Ekvator'a olan uzaklık\nII. Ortalama yükselti\nIII. Başlangıç meridyeni ile arasındaki zaman farkı\nIV. Yüz ölçümü\n\nYukarıdakilerden hangileri bir yerin matematik konumunu belirlerken kullanılır?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "I ve II"},
            {"key": "B", "text": "II ve III"},
            {"key": "C", "text": "II ve IV"},
            {"key": "D", "text": "I ve III"},
            {"key": "E", "text": "III ve IV"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Ekvator'a uzaklık (Enlem/Paralel) ve Başlangıç meridyenine zaman farkı (Boylam/Meridyen) matematik konumdur."
    },
    {
        "id": "cogr1-q12",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 12,
        "questionText": "Aşağıdakilerden hangisi Türkiye'nin orta kuşakta yer aldığının bir göstergesidir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Kuzeye doğru gidildikçe çizgisel hızın azalması"},
            {"key": "B", "text": "Yıl içinde belirgin sıcaklık farklarının ve mevsimlerin oluşması"},
            {"key": "C", "text": "En uzun gündüzün 21 Haziran'da yaşanması"},
            {"key": "D", "text": "Kısa mesafelerde iklim değişimlerinin yaşanması"},
            {"key": "E", "text": "21 Mart tarihinde 12 saat gündüz yaşanması"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Dört mevsimin belirgin yaşanması ve yıllık sıcaklık farkları Orta Kuşak sonucudur."
    },
    {
        "id": "cogr1-q13",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 13,
        "questionText": "Aşağıda verilen kentlerden hangisinin yıl boyu alacakaranlık (tan ve grup) süresi diğerlerinden daha uzundur?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Van"},
            {"key": "B", "text": "Ardahan"},
            {"key": "C", "text": "Mersin"},
            {"key": "D", "text": "Amasya"},
            {"key": "E", "text": "İzmir"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Kuzeye gidildikçe çizgisel hız azaldığı için Güneş daha yavaş doğup batar; Ardahan'da alacakaranlık süresi en uzundur."
    },
    {
        "id": "cogr1-q14",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 14,
        "questionText": "Türkiye 36°-42° Kuzey paralelleri ile 26°-45° Doğu meridyenleri arasında yer almaktadır.\n\nAşağıda verilen özelliklerden hangisi Türkiye'nin matematik konumuyla açıklanamaz?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Dört mevsimin belirgin olarak yaşanması"},
            {"key": "B", "text": "Antalya'dan Sinop'a doğru gidildikçe gece-gündüz süre farkının artması"},
            {"key": "C", "text": "Dağların güney yamacının yıl boyunca daha fazla güneşlenmesi"},
            {"key": "D", "text": "Üç kıtanın birbirine en yakın olduğu yerde bulunması"},
            {"key": "E", "text": "Kuzeye doğru gidildikçe yer çekiminin artması"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Kıtalara, denizlere ve boğazlara göre konum Özel (Göreceli) konumdur."
    },
    {
        "id": "cogr1-q15",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 15,
        "questionText": "Ankara'dan günübirlik bir geziye katılan Atilla, gittiği yerde Güneş'in doğuş ve batış süresinin (alacakaranlık) kısaldığını ve yerel saatin daha geri olduğunu gözlemlemiştir.\n\nAtilla aşağıda verilen kentlerden hangisine gitmiş olabilir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Safranbolu"},
            {"key": "B", "text": "Fethiye"},
            {"key": "C", "text": "İskenderun"},
            {"key": "D", "text": "Şırnak"},
            {"key": "E", "text": "Sakarya"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Alacakaranlık kısaldığı için daha güneye, yerel saat daha geri olduğu için daha batıya gitmiştir (Güneybatı = Fethiye)."
    },
    {
        "id": "cogr1-q16",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 16,
        "questionText": "Aşağıda verilen kentlerden hangisinde yıl boyunca yerel saat ile ulusal saat (45° Doğu Iğdır) arasındaki farkın daha az olması beklenir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Gümüşhane"},
            {"key": "B", "text": "İzmir"},
            {"key": "C", "text": "Hatay"},
            {"key": "D", "text": "Artvin"},
            {"key": "E", "text": "Antalya"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Artvin 45° Doğu boylamına en yakın il olduğu için yerel saat farkı en azdır."
    },
    {
        "id": "cogr1-q17",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 17,
        "questionText": "I. Yer çekimi artar.\nII. Gurup ve tan süresi kısalır.\nIII. Gölge boyu uzar.\nIV. Güneş ışınlarının geliş açısı büyür.\n\nHaritada belirtilen ok yönünde (Güneyden Kuzeye) ilerlendiğinde yukarıda verilen durumlardan hangilerinin yaşanması beklenmez?",
        "hasImage": True,
        "image": "assets/questions/cogr1_q17_map.png",
        "options": [
            {"key": "A", "text": "Yalnız II"},
            {"key": "B", "text": "I ve II"},
            {"key": "C", "text": "I ve IV"},
            {"key": "D", "text": "II ve III"},
            {"key": "E", "text": "II ve IV"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>Kuzeye gidildikçe tan/gurup süresi uzar (kısalmaz) ve Güneş açısı küçülür (büyümez)."
    },
    {
        "id": "cogr1-q18",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 18,
        "questionText": "Haritada aynı enlem üzerinde yer alan üç il (Çanakkale, Ankara, Erzurum) gösterilmiştir.\n\nBelirtilen illerimizin ortak özellikleri arasında aşağıdakilerden hangisi yer almaz?",
        "hasImage": True,
        "image": "assets/questions/cogr1_q18_map.png",
        "options": [
            {"key": "A", "text": "Güneş ışınlarının geliş açısı"},
            {"key": "B", "text": "Çizgisel hızları"},
            {"key": "C", "text": "Ekvator'a olan kuş uçuşu uzaklıkları"},
            {"key": "D", "text": "Yükselti ortalamaları"},
            {"key": "E", "text": "Öğle vakti gölge boyları ve yönleri"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Batıdan doğuya doğru yükselti artar; dolayısıyla yükselti ortalamaları aynı değildir."
    },
    {
        "id": "cogr1-q19",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 19,
        "questionText": "Yukarıdaki haritada yaklaşık aynı boylam üzerinde yer alan Gümüşhane ve Tunceli illeri gösterilmiştir.\n\nBuna göre, verilen kentlerle ilgili aşağıdakilerden hangisi söylenemez?",
        "hasImage": True,
        "image": "assets/questions/cogr1_q19_map.png",
        "options": [
            {"key": "A", "text": "Başlangıç meridyenine olan uzaklıkları eşittir."},
            {"key": "B", "text": "Öğle vakitleri yıl boyunca aynı anda yaşanır."},
            {"key": "C", "text": "Ulusal saat ile yerel saatleri arasındaki zaman farkı aynıdır."},
            {"key": "D", "text": "Yerel saatleri yıl boyunca aynıdır."},
            {"key": "E", "text": "Gün içinde gölgelerinin en kısa olduğu an aynıdır."}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>Meridyen aralıkları kutuplara doğru daraldığı için kuzeydeki Gümüşhane Başlangıç Meridyenine km olarak daha yakındır."
    },
    {
        "id": "cogr1-q20",
        "testId": "cogr1",
        "testTitle": "Coğrafya Video Tarama Testi 1",
        "topicId": "cogr_tarama_1",
        "topicName": "Coğrafya Video Tarama 1",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 20,
        "questionText": "Türkiye ile ilgili aşağıda verilen özelliklerden hangisinde enlemin etkisinden söz edilemez?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Cephesel yağışların görülmesi"},
            {"key": "B", "text": "Aynı anda farklı mevsim koşullarının yaşanabilmesi"},
            {"key": "C", "text": "Akdeniz'de kıyı turizm süresinin Karadeniz'den uzun olması"},
            {"key": "D", "text": "Aydın'da aynı tarım ürününün Çanakkale'den önce olgunlaşması"},
            {"key": "E", "text": "Dört mevsimin belirgin yaşanabilmesi"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Aynı anda farklı iklim ve mevsim koşullarının görülmesi yer şekilleri ve yükseltinin (Göreceli Konum) sonucudur."
    }
]

cogr2_questions = [
    {
        "id": "cogr2-q1",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 1,
        "questionText": "21 Haziran günü yukarıda verilen Türkiye haritasındaki kentlerden (Sinop, Kocaeli, Isparta, Şırnak, Kars) hangisinde Güneş daha erken doğar?",
        "hasImage": True,
        "image": "assets/questions/cogr2_q1_map.png",
        "options": [
            {"key": "A", "text": "Isparta"},
            {"key": "B", "text": "Kars"},
            {"key": "C", "text": "Sinop"},
            {"key": "D", "text": "Kocaeli"},
            {"key": "E", "text": "Hakkâri"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>21 Haziran'da kuzeye ve doğuya gidildikçe gündüz süresi uzar ve Güneş daha erken doğar. Kars en kuzeydoğuda yer alır."
    },
    {
        "id": "cogr2-q2",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 2,
        "questionText": "Yukarıda verilen Türkiye haritasındaki beş ayrı noktanın hangisinde 21 Aralık'ta yaşanan gece süresi diğerlerine göre daha uzundur?",
        "hasImage": True,
        "image": "assets/questions/cogr2_q2_map.png",
        "options": [
            {"key": "A", "text": "V"},
            {"key": "B", "text": "IV"},
            {"key": "C", "text": "III"},
            {"key": "D", "text": "II"},
            {"key": "E", "text": "I"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>21 Aralık'ta kuzeye gidildikçe gece süresi uzar; haritada en kuzeyde yer alan nokta III (Sinop civarı)'tür."
    },
    {
        "id": "cogr2-q3",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 3,
        "questionText": "Türkiye'de hangi tarihten sonra öğle vakti gölge boyları kısalmaya başlar?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "21 Haziran"},
            {"key": "B", "text": "23 Eylül"},
            {"key": "C", "text": "15 Şubat"},
            {"key": "D", "text": "21 Aralık"},
            {"key": "E", "text": "21 Mart"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>21 Aralık'ta gölge boyu en uzundur; 21 Aralık'tan sonra Güneş ışınlarının geliş açısı büyüdüğü için gölge boyları kısalmaya başlar."
    },
    {
        "id": "cogr2-q4",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 4,
        "questionText": "Türkiye'de en uzun gece süresinin yaşandığı tarihte (21 Aralık) Elazığ'dan aşağıdaki kentlerin hangisine gidilirse ulaşılan kentteki gece süresinin daha kısa olacağı söylenebilir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Rize"},
            {"key": "B", "text": "Çankırı"},
            {"key": "C", "text": "Kırklareli"},
            {"key": "D", "text": "Kars"},
            {"key": "E", "text": "Hakkâri"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>21 Aralık'ta güneye gidildikçe gece süresi kısalır; Hakkâri Elazığ'ın güneyinde yer alır."
    },
    {
        "id": "cogr2-q5",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 5,
        "questionText": "Yukarıda İstanbul'da Güneş'in gün içindeki ufuk konumu verilirken, aynı anda Türkiye'de başka bir ilde (X) Güneş'in konumu gösterilmiştir. Coğrafi konum özellikleri dikkate alındığında X şehri aşağıdakilerden hangisi olabilir?",
        "hasImage": True,
        "image": "assets/questions/cogr2_q5_map.png",
        "options": [
            {"key": "A", "text": "Bursa"},
            {"key": "B", "text": "Sinop"},
            {"key": "C", "text": "Gaziantep"},
            {"key": "D", "text": "Edirne"},
            {"key": "E", "text": "Erzurum"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>X kentinde Güneş batmaya daha yakındır yani yerel saati daha ileridir."
    },
    {
        "id": "cogr2-q6",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 6,
        "questionText": "Kırşehir'den yola çıkan bir araştırma grubu ulaştığı yerin;\n• Yerel saatinin daha geri (Batıya gitmiş)\n• Çizgisel hızının daha fazla (Güneye gitmiş)\n• Grup ve tan süresinin daha kısa (Güneye gitmiş)\nolduğunu gözlemlemiştir.\n\nBu araştırma grubu haritada gösterilen ok yönlerinden hangisine doğru gitmiştir?",
        "hasImage": True,
        "image": "assets/questions/cogr2_q6_map.png",
        "options": [
            {"key": "A", "text": "I"},
            {"key": "B", "text": "II"},
            {"key": "C", "text": "III"},
            {"key": "D", "text": "IV"},
            {"key": "E", "text": "V"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Batı ve Güney yönlerinin bileşkesi Güneybatı (IV numaralı ok)'dur."
    },
    {
        "id": "cogr2-q7",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 7,
        "questionText": "Aşağıda verilen kentlerin hangisinin yerel saatiyle ortak saat (45° Doğu Iğdır) arasındaki zaman farkı daha azdır?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Hakkâri"},
            {"key": "B", "text": "İzmir"},
            {"key": "C", "text": "Ankara"},
            {"key": "D", "text": "Konya"},
            {"key": "E", "text": "Zonguldak"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>45° Doğu boylamına en yakın olan Hakkâri'de yerel saat ile ulusal saat farkı en azdır."
    },
    {
        "id": "cogr2-q8",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 8,
        "questionText": "Ekvator üzerinde yıl boyunca 12 saat gece 12 saat gündüz yaşanırken, kutuplara doğru gittikçe gece ile gündüz arasındaki zaman farkı artmaktadır.\n\nBuna göre, Türkiye'de aşağıdaki dönemlerin hangisinde gündüz süresi 12 saatten daha fazladır?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Ekim – Kasım"},
            {"key": "B", "text": "Şubat – Mart"},
            {"key": "C", "text": "Aralık – Ocak"},
            {"key": "D", "text": "Kasım – Aralık"},
            {"key": "E", "text": "Nisan – Mayıs"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>21 Mart ile 23 Eylül arasında Kuzey Yarım Küre'de gündüz süresi 12 saatten fazladır (Nisan - Mayıs)."
    },
    {
        "id": "cogr2-q9",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 9,
        "questionText": "Aşağıda verilen Türkiye'ye ait özelliklerden hangisi Türkiye'nin jeopolitik önemini diğerlerine göre daha az etkiler?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Dört mevsimin belirgin olarak yaşanması"},
            {"key": "B", "text": "İstanbul ve Çanakkale boğazlarına sahip olması"},
            {"key": "C", "text": "Güçlü bir kara ordusuna sahip olması"},
            {"key": "D", "text": "Asya ve Avrupa kıtaları arasında köprü olması"},
            {"key": "E", "text": "Petrol zengini Hazar Havzası ve Orta Doğu'ya komşu olması"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>Dört mevsimin yaşanması iklimsel/matematik konum özelliğidir; jeopolitik stratejik gücü diğerleri kadar doğrudan etkilemez."
    },
    {
        "id": "cogr2-q10",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 10,
        "questionText": "Türkiye;\n• Kuzey Yarım Küre'de,\n• Yengeç Dönencesi'nin kuzeyinde,\n• Orta Kuşak'ta yer alır.\n\nBu bilgilere göre aşağıda verilenlerden hangisine ulaşılamaz?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Zonguldak'ta deniz suyu tuzluluğu Muğla'dan daha azdır."},
            {"key": "B", "text": "Toroslar'ın güney yamacındaki karlar kuzey yamacından daha erken erir."},
            {"key": "C", "text": "Doğu Karadeniz kıyılarında yıllık yağış miktarı daha fazladır."},
            {"key": "D", "text": "Hatay'da Güneş ışınlarının geliş açısı yıl içinde 90° olmaz."},
            {"key": "E", "text": "Türkiye Batı rüzgârları kuşağında yer alır."}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Doğu Karadeniz'in fazla yağış alması yer şekilleri ve denize paralel uzanan dağların (Özel Konum) sonucudur."
    },
    {
        "id": "cogr2-q11",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 11,
        "questionText": "Aşağıdakilerden hangisi Türkiye'yi dolaylı yönden ilgilendiren sorunlardan biridir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Irak sorunu"},
            {"key": "B", "text": "Kosova sorunu"},
            {"key": "C", "text": "Batı Trakya sorunu"},
            {"key": "D", "text": "Ermenistan sorunu"},
            {"key": "E", "text": "Suriye ile Fırat'ın sularını paylaşma sorunu"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Sınır komşularımız doğrudan; Kosova, Bosna, Filistin gibi bölgeler dolaylı sorunlarımızdır."
    },
    {
        "id": "cogr2-q12",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 12,
        "questionText": "Türkiye'nin aşağıda verilen sıcaklık özelliklerinden hangisi özel (göreceli) konumundan etkilenmez?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Antalya'nın Zonguldak'tan daha sıcak olması"},
            {"key": "B", "text": "Kışın Aydın'ın Konya'dan daha sıcak olması"},
            {"key": "C", "text": "Ankara'nın Erzurum'dan daha sıcak olması"},
            {"key": "D", "text": "Kışın Samsun'un Aksaray'dan daha sıcak olması"},
            {"key": "E", "text": "Yazın Şanlıurfa'nın Mersin'den daha sıcak olması"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>Antalya'nın Zonguldak'tan sıcak olması güney-kuzey enlem (Matematik Konum) farkıdır."
    },
    {
        "id": "cogr2-q13",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 13,
        "questionText": "Aşağıdaki Türkiye haritasında bazı sınır kapıları gösterilmiştir (İpsala, Kapıkule, Gürbulak, Habur, Cilvegözü).\n\nVerilen sınır kapılarından hangisinin haritadaki yeri yanlış gösterilmiştir?",
        "hasImage": True,
        "image": "assets/questions/cogr2_q13_map.png",
        "options": [
            {"key": "A", "text": "İpsala"},
            {"key": "B", "text": "Kapıkule"},
            {"key": "C", "text": "Gürbulak"},
            {"key": "D", "text": "Habur"},
            {"key": "E", "text": "Cilvegözü"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Kapıkule Bulgaristan sınırında yer alır; haritada konumu yanlış işaretlenmiştir."
    },
    {
        "id": "cogr2-q14",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 14,
        "questionText": "Türkiye, bulunduğu coğrafi konum nedeniyle birçok farklı ticari, ekonomik, askerî ve siyasi uluslararası kuruluşa üyedir.\n\nBuna göre, aşağıdakilerden hangisi Türkiye'nin üye olduğu uluslararası kuruluşlardan biri değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "NAFTA"},
            {"key": "B", "text": "İİT / İKO"},
            {"key": "C", "text": "KEİ"},
            {"key": "D", "text": "NATO"},
            {"key": "E", "text": "OECD"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>NAFTA Kuzey Amerika Serbest Ticaret Anlaşması olup üyeleri ABD, Kanada ve Meksika'dır."
    },
    {
        "id": "cogr2-q15",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 15,
        "questionText": "Türkiye'nin, aşağıdaki ülkelerin hangisiyle olan kara sınırı diğerlerine göre daha kısadır?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Gürcistan"},
            {"key": "B", "text": "Yunanistan"},
            {"key": "C", "text": "Ermenistan"},
            {"key": "D", "text": "Bulgaristan"},
            {"key": "E", "text": "Irak"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Yunanistan kara sınırımız 212 km olup verilen seçenekler arasındaki en kısa sınırdır."
    },
    {
        "id": "cogr2-q16",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 16,
        "questionText": "Aşağıdakilerden hangisi, Türkiye'yi doğrudan ilgilendiren sorunlardan biridir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Dağlık Karabağ Sorunu"},
            {"key": "B", "text": "Doğu Akdeniz'deki petrol ve doğal gaz arama faaliyetleri"},
            {"key": "C", "text": "Çin'de Doğu Türkistan / Uygur Türklerine uygulanan baskı sorunu"},
            {"key": "D", "text": "Filistin Sorunu"},
            {"key": "E", "text": "Bosna-Hersek Sorunu"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Doğu Akdeniz yetki alanları Türkiye'nin doğrudan egemenlik hakları ile ilgilidir."
    },
    {
        "id": "cogr2-q17",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 17,
        "questionText": "Eski buzul vadilerinin deniz suları altında kalmasıyla fiyort tipi kıyılar oluşur.\n\nTürkiye'de fiyort tipi kıyıların görülmemesinin temel nedeni aşağıdakilerden hangisidir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Yüksek ve engebeli bir ülke olması"},
            {"key": "B", "text": "Dağların doğu-batı doğrultusunda uzanması"},
            {"key": "C", "text": "Orta Kuşak'ın ılıman/sıcak güney yarısında (Matematik konum) yer alması"},
            {"key": "D", "text": "Platoların geniş alan kaplaması"},
            {"key": "E", "text": "Kuzey Yarım Küre'de yer alması"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Fiyort kıyılar kutup kuşağına yakın soğuk enlemlerde deniz seviyesine kadar inen buzullarla oluşur. Türkiye ılıman kuşaktadır."
    },
    {
        "id": "cogr2-q18",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 18,
        "questionText": "Türkiye'de 2200 metreden daha yüksek dağlar üzerinde buzul aşındırma ve biriktirme şekilleri görülmektedir.\n\nHaritada işaretlenmiş alanların hangisinde buzul şekillerine rastlanılmaz?",
        "hasImage": True,
        "image": "assets/questions/cogr2_q18_map.png",
        "options": [
            {"key": "A", "text": "I"},
            {"key": "B", "text": "II"},
            {"key": "C", "text": "III"},
            {"key": "D", "text": "IV"},
            {"key": "E", "text": "V"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>I numaralı Marmara / Yıldız Dağları bölgesinde yükselti 2200 metrenin altında olduğu için buzul şekli oluşmamıştır."
    },
    {
        "id": "cogr2-q19",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 19,
        "questionText": "Aşağıdakilerden hangisi Türkiye'de iklim çeşitliliğinin fazla olduğuna kanıt olarak gösterilemez?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Tarım ürünü çeşitliliğinin fazla olması"},
            {"key": "B", "text": "Toprak türlerinin çeşitli olması"},
            {"key": "C", "text": "Maden çeşitliliğinin fazla olması"},
            {"key": "D", "text": "Akarsu rejimlerinin farklılık göstermesi"},
            {"key": "E", "text": "Bitki örtüsü çeşitliliğinin fazla olması"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Maden çeşitliliği jeolojik devirler, volkanizma ve metamorfizma (Jeolojik Yapı) sonucudur; iklimle ilgisi yoktur."
    },
    {
        "id": "cogr2-q20",
        "testId": "cogr2",
        "testTitle": "Coğrafya Video Tarama Testi 2",
        "topicId": "cogr_tarama_2",
        "topicName": "Coğrafya Video Tarama 2",
        "category": "Genel Kültür - Coğrafya",
        "icon": "🌍",
        "questionNumber": 20,
        "questionText": "I. Orojenez (Dağ oluşumu)\nII. Epirojenez (Kıta oluşumu)\nIII. Volkanizma\nIV. Depremler\n\nİç kuvvetler enerjisini yerin derinliklerinden alan yapıcı kuvvetlerdir. Ortaya çıkaran güç aynı olmakla birlikte iç kuvvetlerin gerçekleşme hızları aynı değildir.\n\nYukarıda verilenlerden hangileri yeryüzünü en kısa ve en uzun sürede değiştiren kuvvetler şeklinde kategorilendirilebilir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "En Kısa: Orojenez / En Uzun: Epirojenez"},
            {"key": "B", "text": "En Kısa: Volkanizma / En Uzun: Orojenez"},
            {"key": "C", "text": "En Kısa: Depremler / En Uzun: Orojenez"},
            {"key": "D", "text": "En Kısa: Volkanizma / En Uzun: Epirojenez"},
            {"key": "E", "text": "En Kısa: Depremler / En Uzun: Epirojenez"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>Depremler saniyeler içinde gerçekleşirken, Epirojenez (kıta oluşumu) milyonlarca yıllık jeolojik süreçlerde meydana gelir."
    }
]

tarih1_questions = [
    {
        "id": "tarih1-q1",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 1,
        "questionText": "İslam öncesi Türk devletlerinin ilk ana yurdu olan Orta Asya tarif edilirken aşağıdaki coğrafi isimlerden hangisi kullanılmaz?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Altay Dağları"},
            {"key": "B", "text": "Hazar Denizi"},
            {"key": "C", "text": "Aral Gölü"},
            {"key": "D", "text": "İber Yarımadası"},
            {"key": "E", "text": "Tanrı Dağları"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>İber Yarımadası (İspanya-Portekiz) Avrupa'dadır; Orta Asya sınırları içinde yer almaz."
    },
    {
        "id": "tarih1-q2",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 2,
        "questionText": "Orta Asya'da araştırma yapan tarihçilerin ve arkeologların, İslamiyet öncesi Orta Asya Türk tarihiyle ilgili yaptıkları araştırmalarda aşağıdakilerden hangisiyle karşılaşması beklenemez?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Yazılı taşlar"},
            {"key": "B", "text": "Madenî paralar"},
            {"key": "C", "text": "Kurganlar"},
            {"key": "D", "text": "Medreseler"},
            {"key": "E", "text": "Mezar taşları"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Medreseler İslamiyet'in kabulünden sonra ortaya çıkan eğitim kurumlarıdır."
    },
    {
        "id": "tarih1-q3",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 3,
        "questionText": "İslamiyet öncesi Türk devletlerinde;\nI. Sanat\nII. Askerlik\nIII. Hukuk\nalanlarından hangileri göçebe yaşam tarzından etkilenmiştir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Yalnız I"},
            {"key": "B", "text": "Yalnız II"},
            {"key": "C", "text": "I ve II"},
            {"key": "D", "text": "II ve III"},
            {"key": "E", "text": "I, II ve III"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>Taşınabilir sanat eserleri, ordu-millet anlayışı ve hapis cezalarının kısa süreli olması göçebe yaşamın sonucudur."
    },
    {
        "id": "tarih1-q4",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 4,
        "questionText": "Aşağıdakilerden hangisi İslamiyet öncesi Türk devletlerinde hükümdarlık unvanları arasında yer almaz?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Kağan"},
            {"key": "B", "text": "İdikut"},
            {"key": "C", "text": "İlteber"},
            {"key": "D", "text": "Hakan"},
            {"key": "E", "text": "Sultan"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>Sultan unvanı İslamiyet sonrası Gazneli Mahmut ile başlayan İslami bir unvandır."
    },
    {
        "id": "tarih1-q5",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 5,
        "questionText": "Aşağıdakilerden hangisinin Kurultaya (Toy / Kengeş) katılma hakkı bulunmaz?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Boy beyleri"},
            {"key": "B", "text": "Kam"},
            {"key": "C", "text": "Komutanlar"},
            {"key": "D", "text": "İleri gelenler"},
            {"key": "E", "text": "Hatun"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Din adamları (Kam/Baksı/Şaman) teokratik bir yapı oluşmaması için kurultaya katılamazdı."
    },
    {
        "id": "tarih1-q6",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 6,
        "questionText": "İslamiyet öncesi Türk devletlerinde aşağıdakilerden hangisi hükümet için kullanılan kavramdır?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Buyruk"},
            {"key": "B", "text": "Tudun"},
            {"key": "C", "text": "Bitikçi"},
            {"key": "D", "text": "Tamgacı"},
            {"key": "E", "text": "Ayukı"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>Ayukı hükümet, Aygucı başbakan, Buyruk ise bakan demektir."
    },
    {
        "id": "tarih1-q7",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 7,
        "questionText": "İslamiyet öncesi Türk devletlerinde görülen;\nI. Sınıfsal farkların olmaması\nII. Mimarinin gelişmesi\nIII. Askerî teşkilatın güçlenmesi\ngelişmelerinin hangilerinde göçebe yaşam tarzının etkisinden söz edilebilir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "I ve II"},
            {"key": "B", "text": "Yalnız II"},
            {"key": "C", "text": "Yalnız III"},
            {"key": "D", "text": "II ve III"},
            {"key": "E", "text": "I ve III"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>Toprak mülkiyeti olmadığı için sınıf ayrımı yoktur; hareketli yaşam askerî kabiliyeti geliştirmiştir."
    },
    {
        "id": "tarih1-q8",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 8,
        "questionText": "Aşağıdaki kavram-anlam eşleştirmelerinden hangisi yanlış olarak verilmiştir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Örgin – Taht"},
            {"key": "B", "text": "Tamu – Cennet"},
            {"key": "C", "text": "Tudun – Vergi memuru"},
            {"key": "D", "text": "Tamgacı – Mühürdar"},
            {"key": "E", "text": "Ağılığ – Hazine görevlisi"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Tamu cehennem, Uçmağ cennet anlamına gelir."
    },
    {
        "id": "tarih1-q9",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 9,
        "questionText": "Aşağıdakilerden hangisi İslam öncesi Türk devletlerinde Türk bürokrasisinin bir unsuru değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Bitikçi"},
            {"key": "B", "text": "Baksı"},
            {"key": "C", "text": "Ayukı"},
            {"key": "D", "text": "Tudun"},
            {"key": "E", "text": "Hükümdar"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Baksı din adamı / şaman / ozan olup devlet bürokrasisinin bir memuru değildir."
    },
    {
        "id": "tarih1-q10",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 10,
        "questionText": "Kurultayın ilk Türk devletlerinde;\nI. Yasama\nII. Askerî\nIII. Siyasi\nalanlarından hangilerinde rol oynadığı savunulabilir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Yalnız I"},
            {"key": "B", "text": "Yalnız II"},
            {"key": "C", "text": "I ve II"},
            {"key": "D", "text": "I ve III"},
            {"key": "E", "text": "I, II ve III"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>Kurultay töre koyma (yasama), savaş kararı (askerî) ve kağan seçimi/yönetim (siyasi) yetkilerine sahipti."
    },
    {
        "id": "tarih1-q11",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 11,
        "questionText": "Aşağıdakilerden hangisi ilk Türk devletlerinde hükümdarlık sembolü değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Nevbet"},
            {"key": "B", "text": "Berge"},
            {"key": "C", "text": "Sorguç"},
            {"key": "D", "text": "Tıraz"},
            {"key": "E", "text": "Örgin"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Tıraz İslami dönemde halifenin gönderdiği hilat/elbisedir; İslam öncesi sembol değildir."
    },
    {
        "id": "tarih1-q12",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 12,
        "questionText": "İslamiyet öncesi Türk devletlerinde;\nI. Monarşik\nII. Teokratik\nIII. Federal\nyönetim anlayışlarından hangileri görülür?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Yalnız I"},
            {"key": "B", "text": "Yalnız II"},
            {"key": "C", "text": "I ve II"},
            {"key": "D", "text": "I ve III"},
            {"key": "E", "text": "I, II ve III"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Tek lider (Monarşi) ve ikili teşkilat/boylar birliği (Federal) görülür; teokrasi yoktur."
    },
    {
        "id": "tarih1-q13",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 13,
        "questionText": "İslamiyet öncesi Türk devletlerinde aşağıdakilerden hangisinde göçebe yaşamın olumlu/geliştirici bir etkisi yoktur?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Yazılı hayata geç geçilmesi"},
            {"key": "B", "text": "Askerî yapının güçlenmesi"},
            {"key": "C", "text": "Mimari alanda gelişimin sağlanması"},
            {"key": "D", "text": "Özel mülkiyetin gelişmemesi"},
            {"key": "E", "text": "Hapis cezalarının kısa süreli olması"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Göçebe yaşam kalıcı mimari eserlerin gelişmesini engellemiştir."
    },
    {
        "id": "tarih1-q14",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 14,
        "questionText": "İslamiyet öncesi Türk devletlerinde yazışmalardan sorumlu olan ve Kurultayın kâtipleri olarak da bilinen görevli aşağıdakilerden hangisidir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Tudun"},
            {"key": "B", "text": "Tamgacı"},
            {"key": "C", "text": "Ayukı"},
            {"key": "D", "text": "Bitikçi"},
            {"key": "E", "text": "Ulak"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Bitikçi devlet yazışmalarını yürüten kâtiptir."
    },
    {
        "id": "tarih1-q15",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 15,
        "questionText": "İslamiyet öncesi Türk devletlerinde aşağıdakilerden hangisi hükümdarın görevleri arasında yer almaz?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Milleti refah ve barış içinde yaşatmak"},
            {"key": "B", "text": "Orduyu idare etmek"},
            {"key": "C", "text": "Töreyi uygulamak"},
            {"key": "D", "text": "Dini yaymak"},
            {"key": "E", "text": "Halkın ihtiyaçlarını karşılamak"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>İslam öncesi Türklerde dini zorla yayma görevi yoktur, dini hoşgörü esastır."
    },
    {
        "id": "tarih1-q16",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 16,
        "questionText": "İslamiyet öncesi Türk ordusunda bugünkü flama ve sancak yerine kullanılan ve hükümdarlık sembolü olan kavram aşağıdakilerden hangisidir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Sorguç"},
            {"key": "B", "text": "Tuğ"},
            {"key": "C", "text": "Örgin"},
            {"key": "D", "text": "Otağ"},
            {"key": "E", "text": "Ongun"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Tuğ hükümdarlık ve ordu sancağı / flamasıdır."
    },
    {
        "id": "tarih1-q17",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 17,
        "questionText": "İslamiyet öncesi Türklerde \"Budun\" kavramının karşılığı aşağıdakilerden hangisidir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Millet"},
            {"key": "B", "text": "Boylar birliği"},
            {"key": "C", "text": "Bakan"},
            {"key": "D", "text": "Meclis"},
            {"key": "E", "text": "Töre"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>Budun millet anlamına gelir."
    },
    {
        "id": "tarih1-q18",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 18,
        "questionText": "İslam öncesi Türk devletlerinde sınıfsal toplum yapısının olmaması aşağıdakilerden hangisinin sonucudur?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Veraset anlayışı"},
            {"key": "B", "text": "Ordu-millet anlayışı"},
            {"key": "C", "text": "İkili teşkilat"},
            {"key": "D", "text": "Göçebe yaşam"},
            {"key": "E", "text": "Kut inancı"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Göçebe yaşamda toprak mülkiyeti devlete ait olduğu için sınıfsal ayrım oluşmamıştır."
    },
    {
        "id": "tarih1-q19",
        "testId": "tarih1",
        "testTitle": "Genel Tarih Video Tarama Testi 1",
        "topicId": "tarih_tarama_1",
        "topicName": "Genel Tarih Video Tarama 1",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 19,
        "questionText": "İlk Türk devletlerinde \"ülkenin, hanedanın ortak malı sayılması\" anlayışı aşağıdakilerden hangisini beraberinde getirmiştir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Ordu-millet anlayışını"},
            {"key": "B", "text": "Devletin kısa sürede yıkılmasını"},
            {"key": "C", "text": "Sosyal hayatın canlanmasını"},
            {"key": "D", "text": "Merkezî otoritenin güçlenmesini"},
            {"key": "E", "text": "Özel mülkiyetin gelişmesini"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Hanedan ortak malı anlayışı taht kavgalarına ve devletlerin kısa sürede yıkılmasına yol açmıştır."
    }
]

tarih2_questions = [
    {
        "id": "tarih2-q1",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 1,
        "questionText": "Aşağıdakilerden hangisi ilk Türk devletlerinde hükümdarların kullandığı unvanlar arasında yer almaz?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Emir"},
            {"key": "B", "text": "Tanhu"},
            {"key": "C", "text": "Yabgu"},
            {"key": "D", "text": "Erkin"},
            {"key": "E", "text": "İlteriş"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>Emir unvanı İslamiyet'in kabulünden sonra kullanılan bir unvandır."
    },
    {
        "id": "tarih2-q2",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 2,
        "questionText": "Orta Asya Türk devletlerinde, devlet genel olarak doğu ve batı şeklinde yönetilmiştir. Bu bölünmede devletin doğu kanadını hakan, batı kanadını hanedanın erkek üyelerinden biri (Yabgu) yönetirdi.\n\nDevletin bu şekilde yönetilmesi aşağıdakilerden hangisi ile ifade edilmiştir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Veraset anlayışı"},
            {"key": "B", "text": "Merkeziyetçilik"},
            {"key": "C", "text": "İkili teşkilat"},
            {"key": "D", "text": "Kut anlayışı"},
            {"key": "E", "text": "Feodal yapı"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Doğu-batı ayrımı ikili teşkilat (federal yapı) olarak adlandırılır."
    },
    {
        "id": "tarih2-q3",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 3,
        "questionText": "Aşağıdakilerden hangisi İslam öncesi Türk devletlerinde yönetim ile ilgili bir kavram değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Toy"},
            {"key": "B", "text": "Şad"},
            {"key": "C", "text": "Yabgu"},
            {"key": "D", "text": "Kam"},
            {"key": "E", "text": "Tudun"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Kam din adamı / şaman olup yönetimle ilgili bir makam veya unvan değildir."
    },
    {
        "id": "tarih2-q4",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 4,
        "questionText": "İslamiyet öncesi dönemlerde Türklerin konargöçer bir yaşam sürdürmeleri, onların bazı alanlarda gelişmesini doğrudan engellemiştir.\n\nAşağıdakilerden hangisi bu engellenen alanlardan biri değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Mimari"},
            {"key": "B", "text": "Yazılı hukuk"},
            {"key": "C", "text": "El sanatları"},
            {"key": "D", "text": "Resim"},
            {"key": "E", "text": "Tarım"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Taşınabilir el sanatları (dokumacılık, madencilik, deri) göçebelik döneminde çok gelişmiştir."
    },
    {
        "id": "tarih2-q5",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 5,
        "questionText": "İlk Türk devletlerinde, devlet \"hükümdar ailesinin ortak malıdır\" anlayışına dayanmaktaydı.\n\nBu anlayışın benimsenmesi aşağıdakilerden hangisine yol açmamıştır?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Kurulan devletlerin kısa ömürlü olmasına"},
            {"key": "B", "text": "Özel mülkiyetin gelişmesine"},
            {"key": "C", "text": "Ülkenin hanedan üyelerince yönetilmesine"},
            {"key": "D", "text": "İktidarı ele geçirmek isteyenlerin sayısının çoğalmasına"},
            {"key": "E", "text": "Taht kavgalarının çıkmasına"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Toprak hanedanın/devletin olduğu için özel mülkiyet gelişmemiştir."
    },
    {
        "id": "tarih2-q6",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 6,
        "questionText": "İlk Türk devletlerinde kağanın, devlet adamları ve komutanlarla yapmış olduğu toplantıya kurultay denirdi. Bu toplantılarda kağanın sağında ve solunda bulunan devlet adamları bulundukları mevki ve rütbeye göre otururlardı.\n\nAşağıdakilerden hangisi kurultayda oturma sırasını belirleyen töreye verilen isimdir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Toygun"},
            {"key": "B", "text": "Ulus"},
            {"key": "C", "text": "Küç"},
            {"key": "D", "text": "İkbal"},
            {"key": "E", "text": "Orun"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>Orun protokol ve oturma düzeni sırasıdır."
    },
    {
        "id": "tarih2-q7",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 7,
        "questionText": "Türklerde yıkılan bir devletin yerine hemen yenisinin kurulması, Türklerin hangi özelliği ile açıklanabilir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Cihan hâkimiyeti anlayışına sahip olmaları"},
            {"key": "B", "text": "Teşkilatçı yeteneklerinin gelişmiş olması"},
            {"key": "C", "text": "Yardımseverlik duygusuna sahip olmaları"},
            {"key": "D", "text": "Göçebe hayat sürmeleri"},
            {"key": "E", "text": "Gök Tanrı dinine inanmaları"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Teşkilatçılık kabiliyeti yeni devlet kurmayı kolaylaştırmıştır."
    },
    {
        "id": "tarih2-q8",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 8,
        "questionText": "Aşağıdakilerden hangisi İslamiyet öncesi Türk devletlerinde toplumu oluşturan unsurlardan biri değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Urug"},
            {"key": "B", "text": "Boy"},
            {"key": "C", "text": "Oğuş"},
            {"key": "D", "text": "Tayanç"},
            {"key": "E", "text": "Budun"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Tayanç danışman/müşavir demektir; sosyal toplum basamağı değildir."
    },
    {
        "id": "tarih2-q9",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 9,
        "questionText": "İslamiyet öncesi Türklerin konargöçer yaşam tarzı sürmeleri Türklerde aşağıdaki hangi özelliğin ortaya çıkmasında etkili olmamıştır?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Savaşçı bir topluluk olmalarında"},
            {"key": "B", "text": "Zorluklara sabırla dayanabilen bir millet olmalarında"},
            {"key": "C", "text": "Hızlı ve disiplinli hareket etmelerinde"},
            {"key": "D", "text": "Devletlerini ikili teşkilatla yönetmelerinde"},
            {"key": "E", "text": "Kadın-erkek herkesin savaş sanatını iyi bilmelerinde"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>İkili teşkilat idari ve coğrafi yönetim yöntemidir, göçebelikle doğrudan ilgili değildir."
    },
    {
        "id": "tarih2-q10",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 10,
        "questionText": "Aşağıdakilerden hangisi Türk devletlerinde devlet yönetiminin özelliklerinden biri değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Herkesin kurultaya katılma hakkının olması"},
            {"key": "B", "text": "Ülkenin ikili teşkilat halinde yönetilmesi"},
            {"key": "C", "text": "Devlet yönetiminde törelere uyma zorunluluğunun olması"},
            {"key": "D", "text": "Hatunun kurultaya katılması"},
            {"key": "E", "text": "Devlet yönetme yetkisinin hükümdara Tanrı tarafından verildiğine inanılması"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>Kurultaya sadece boy beyleri, hatun ve komutanlar katılabilirdi."
    },
    {
        "id": "tarih2-q11",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 11,
        "questionText": "İslamiyet öncesi Türk geleneğinde, devlet toprakları \"hükümdar ailesinin ortak malı sayılırdı\". Bu gelenek sonucu devletin toprakları prensler arasında bölüşülerek yönetilir ve böylece federal bir yapı ortaya çıkardı.\n\nBu durum aşağıdakilerden hangisine neden olmuştur?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Merkezî otoritenin zayıflamasına"},
            {"key": "B", "text": "Askerî teşkilatın güçlenmesine"},
            {"key": "C", "text": "Taht kavgalarının sona ermesine"},
            {"key": "D", "text": "Türk siyasi birliğinin sağlanmasına"},
            {"key": "E", "text": "Toplumsal dayanışmaya"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>Ülkenin prensler arasında bölünmesi merkezî otoriteyi zayıflatmış ve taht kavgalarına yol açmıştır."
    },
    {
        "id": "tarih2-q12",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 12,
        "questionText": "İlk Türk devletlerinde sosyal yapının en üst kademesini oluştururdu. Türk toprağı, halk bağımsızlığı ve töresi ile siyasi bir kuruluştu. Türkler için kutsal bir kurum olan bu yapının başında kağan bulunurdu.\n\nYukarıda sözü edilen yapı aşağıdakilerden hangisidir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "İl (Devlet)"},
            {"key": "B", "text": "Oğuş"},
            {"key": "C", "text": "Urug"},
            {"key": "D", "text": "Bodun"},
            {"key": "E", "text": "Boy"}
        ],
        "correctAnswer": "A",
        "explanation": "Doğru Cevap: <strong>A</strong><br>İl (El) devlet anlamına gelir ve teşkilatlanmanın en üst basamağıdır."
    },
    {
        "id": "tarih2-q13",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 13,
        "questionText": "Asya Hun Devleti'nden başlayarak Orta Asya'da kurulan Türk devletlerinde hâkimiyetin kaynağı ilahi bir güç olan Gök Tanrı'ya dayanıyordu. Bu anlayışa göre en yüce varlık ve tek yaratıcı olarak kabul edilen Gök Tanrı yeryüzünü doğrudan kendisi değil yetki verdiği kağan eliyle yönetiyordu.\n\nYukarıda sözü edilen anlayış aşağıdakilerden hangisidir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Tuğ"},
            {"key": "B", "text": "Kut"},
            {"key": "C", "text": "Töre"},
            {"key": "D", "text": "Veraset"},
            {"key": "E", "text": "Toy"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Gök Tanrı tarafından hükümdara verilen yönetme yetkisine Kut denir."
    },
    {
        "id": "tarih2-q14",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 14,
        "questionText": "I. Göçebe ve yarı göçebe yaşam tarzının benimsenmesi\nII. Özel mülkiyetin gelişmemesi\nIII. Çadır sanatının gelişmesi\nIV. Ölümden sonra ikinci hayatın varlığına inanılması\nV. Savaşçı karaktere sahip olunması\n\nYukarıdakilerden hangisi bozkır kültürünün doğurduğu özelliklerden biri değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "I"},
            {"key": "B", "text": "II"},
            {"key": "C", "text": "III"},
            {"key": "D", "text": "IV"},
            {"key": "E", "text": "V"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Ahiret inancı bozkır coğrafi kültüründen değil, Gök Tanrı dininden kaynaklanır."
    },
    {
        "id": "tarih2-q15",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 15,
        "questionText": "İslamiyet öncesi Orta Asya'da kurulan Türk devletlerinin yıkılmasında aşağıdakilerden hangisinin etkisi daha çoktur?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Orta Asya'nın dağlık bir coğrafya olması"},
            {"key": "B", "text": "Veraset anlayışına göre devletin hanedan üyeleri arasında bölüşülmesi"},
            {"key": "C", "text": "Türklerin Orta Asya'da iyi bir devlet örgütü kuramamış olmaları"},
            {"key": "D", "text": "Türklerin boylar halinde yaşamaları"},
            {"key": "E", "text": "Türklerin yerleşik bir hayat düzeninden uzak kalmaları"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Veraset sistemi ve taht kavgaları devletlerin kısa sürede parçalanıp yıkılmasının ana sebebidir."
    },
    {
        "id": "tarih2-q16",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 16,
        "questionText": "Aşağıdakilerden hangisi İslamiyet öncesi Türk devletlerinin özelliklerinden biri değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Hükümdarlık makamının kutlu sayılması"},
            {"key": "B", "text": "Ülkenin hanedan üyeleri arasında bölüşülerek yönetilmesi"},
            {"key": "C", "text": "Sosyal yaşayışta sınıf ayrıcalığına yer verilmesi"},
            {"key": "D", "text": "Ölüler için \"Yuğ\" töreni yapılması"},
            {"key": "E", "text": "Sanatta üsluplaştırılmış hayvan motiflerine yer verilmesi"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Türklerde kölelik ve soyluluk gibi sınıf ayrımı hiçbir zaman olmamıştır."
    },
    {
        "id": "tarih2-q17",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 17,
        "questionText": "İlk kez yirmi üç okul açarak örgün eğitim yapan ve eğitime verdiği önemi \"Çocuğunu öğretmene ver, ondan alıp saraya ver\" atasözüyle dile getiren devlet aşağıdakilerden hangisidir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Asya Hunları"},
            {"key": "B", "text": "Uygurlar"},
            {"key": "C", "text": "Kök Türkler"},
            {"key": "D", "text": "Hazarlar"},
            {"key": "E", "text": "Kırgızlar"}
        ],
        "correctAnswer": "B",
        "explanation": "Doğru Cevap: <strong>B</strong><br>Uygurlar yerleşik hayata geçerek okullar açmış ve örgün eğitimi başlatmıştır."
    },
    {
        "id": "tarih2-q18",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 18,
        "questionText": "Orta Asya'da kurulan Türk devletlerinin tarihi incelendiğinde bu devletlerin önce ikiye bölündüğü ve sonra yıkıldığını görüyoruz.\n\nAşağıdakilerden hangisi bu durumun nedenlerinden biri değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "İkili sistemle yönetilmeleri"},
            {"key": "B", "text": "Boylar halinde yaşamaları"},
            {"key": "C", "text": "Devlet geleneğinde, ülkenin hanedan üyeleri arasında bölüşülmesi"},
            {"key": "D", "text": "Çin'in izlediği içten bölme siyaseti"},
            {"key": "E", "text": "Farklı inançlara sahip olmaları"}
        ],
        "correctAnswer": "E",
        "explanation": "Doğru Cevap: <strong>E</strong><br>İnanç farklılığı yıkılış sebebi değildir; Türk devletlerinde inanç hoşgörüsü vardı."
    },
    {
        "id": "tarih2-q19",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 19,
        "questionText": "Türk devletlerinde \"Ülke toprakları hükümdar ailesinin ortak malıdır.\" anlayışı benimsenmiştir.\n\nBu durumun;\nI. Taht kavgalarının yaşanması\nII. Türk devletlerinin kısa sürede yıkılması\nIII. Merkezî otoritenin güçlü olması\nsonuçlarından hangilerini ortaya çıkardığı söylenebilir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Yalnız I"},
            {"key": "B", "text": "Yalnız III"},
            {"key": "C", "text": "I ve II"},
            {"key": "D", "text": "II ve III"},
            {"key": "E", "text": "I, II ve III"}
        ],
        "correctAnswer": "C",
        "explanation": "Doğru Cevap: <strong>C</strong><br>Hanedanın ortak malı anlayışı taht kavgalarına ve devletlerin kısa sürede yıkılmasına neden olur (I ve II)."
    },
    {
        "id": "tarih2-q20",
        "testId": "tarih2",
        "testTitle": "Genel Tarih Video Tarama Testi 2",
        "topicId": "tarih_tarama_2",
        "topicName": "Genel Tarih Video Tarama 2",
        "category": "Genel Kültür - Tarih",
        "icon": "🏛️",
        "questionNumber": 20,
        "questionText": "Aşağıdakilerden hangisi ilk Türk devletlerinde hükümdarlık (bağımsızlık) sembollerinden biri değildir?",
        "hasImage": False,
        "image": None,
        "options": [
            {"key": "A", "text": "Otağ"},
            {"key": "B", "text": "Ordu"},
            {"key": "C", "text": "Nevbet"},
            {"key": "D", "text": "Orun"},
            {"key": "E", "text": "Berge"}
        ],
        "correctAnswer": "D",
        "explanation": "Doğru Cevap: <strong>D</strong><br>Orun meclisteki protokol oturma sırasıdır; bağımsızlık/hükümdarlık sembolü değildir."
    }
]

all_79 = cogr1_questions + cogr2_questions + tarih1_questions + tarih2_questions

js_content = f"""// EKYS 2027 Odaklı Soru Veritabanı - Coğrafya ve Genel Tarih Video Tarama Testleri (Toplam 79 Soru)
window.EKYS_EXTRACTED_QUESTIONS = {json.dumps(all_79, ensure_ascii=False, indent=2)};
"""

with open('data/questions-db.js', 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f"data/questions-db.js toplam {len(all_79)} soru ile EKSİKSİZ ve KUSURSUZ olarak kaydedildi!")
